//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subtext.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to height must be greater than {0}..
        /// </summary>
        public static string ArgumentOutOfRange_Height
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_Height", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Priority must be in range from 0.0 to 1.0!.
        /// </summary>
        public static string ArgumentOutOfRange_Priority
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_Priority", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to width must be greater than {0}..
        /// </summary>
        public static string ArgumentOutOfRange_Width
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_Width", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///&lt;strong&gt;This sets the subfolder of the host domain that the blog will appear to be located in.&lt;/strong&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;For example, if you enter &amp;#8220;MyBlog&amp;#8221; 
        ///(sans quotes of course) for the application, then the root URL to your blog 
        ///would be &lt;em&gt;http://[HOSTDOMAIN]/MyBlog/Default.aspx&lt;/em&gt;
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///Leave this value blank if you wish to host your blog in the root of your website.
        ///&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;NOTE:&lt;/strong&gt; If you specify a sub-folder, you do not need to set up a virtual directory 
        ///corr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlogsEditor_ApplicationHelpTip
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_ApplicationHelpTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Activated and ready to go..
        /// </summary>
        public static string BlogsEditor_BlogActivated
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_BlogActivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Created..
        /// </summary>
        public static string BlogsEditor_BlogCreated
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_BlogCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Inactivated and sent to a retirement community..
        /// </summary>
        public static string BlogsEditor_BlogDeactivated
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_BlogDeactivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Saved.
        /// </summary>
        public static string BlogsEditor_BlogSaved
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_BlogSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Emptiness is quite Zen. Still, please enter a value for &quot;{0}&quot;..
        /// </summary>
        public static string BlogsEditor_FieldRequired
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_FieldRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Use this page to manage the blogs installed on this server.
        ///For more information on configuring blogs, see the &lt;a href=&apos;http://www.subtextproject.com/Home/Docs/Configuration/tabid/112/Default.aspx&apos; target=&apos;_blank&apos;&gt;configuration docs&lt;/a&gt; (opens a new window).
        ///&lt;/p&gt;.
        /// </summary>
        public static string BlogsEditor_HelpText
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_HelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;Host Domain&lt;/strong&gt; is the domain name for this blog. 
        ///If you never plan on setting up another blog on this server, then you do not have 
        ///to worry about this setting.  However, if you decide to add another blog at a later 
        ///time, it&amp;#8217;s important to update this setting for your initial blog.&lt;/p&gt;
        ///&lt;p&gt;For example, if you are hosting this blog at http://www.example.com/, the Host Domain 
        ///would be &amp;#8220;www.example.com&amp;#8221;.&lt;/p&gt;&lt;p&gt;If you are trying to set this up on your 
        ///own machine for  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BlogsEditor_HostDomainHelpText
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_HostDomainHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Blog.
        /// </summary>
        public static string BlogsEditor_NewBlogLabel
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_NewBlogLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A password is required when creating a blog. Pick a good one..
        /// </summary>
        public static string BlogsEditor_PasswordRequired
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Password and Confirmation do not match. Try retyping your password in both fields..
        /// </summary>
        public static string BlogsEditor_PasswordsDoNotMatch
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_PasswordsDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Update Cancelled. Nothing to see here..
        /// </summary>
        public static string BlogsEditor_UpdateCancelled
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_UpdateCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brevity is rewarded. &quot;{0}&quot; may only have &quot;{1}&quot; characters..
        /// </summary>
        public static string BlogsEditor_ValueTooLong
        {
            get
            {
                return ResourceManager.GetString("BlogsEditor_ValueTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        public static string Calendar_NextMonth
        {
            get
            {
                return ResourceManager.GetString("Calendar_NextMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string Calendar_PreviousMonth
        {
            get
            {
                return ResourceManager.GetString("Calendar_PreviousMonth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Encrypted encoded text &apos;{0}&apos; was not valid..
        /// </summary>
        public static string CaptchaExpired_EncryptedTextNotValid
        {
            get
            {
                return ResourceManager.GetString("CaptchaExpired_EncryptedTextNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Captcha image expired, probably due to recompile making the key out of synch..
        /// </summary>
        public static string CaptchaExpired_KeyOutOfSynch
        {
            get
            {
                return ResourceManager.GetString("CaptchaExpired_KeyOutOfSynch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User waited too long to submit captcha.
        /// </summary>
        public static string CaptchaExpired_WaitedTooLong
        {
            get
            {
                return ResourceManager.GetString("CaptchaExpired_WaitedTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Akismet requires &lt;code&gt;{0}&lt;/code&gt; in order to make web requests. Please ask your hosting provider to &lt;a href=&quot;http://weblogs.asp.net/hosterposter/archive/2006/03/22/440886.aspx&quot; title=&quot;Enabling WebPermission in Medium Trust&quot;&gt;enable this permission&lt;/a&gt;..
        /// </summary>
        public static string Comments_AkismetRequiresPermissionType
        {
            get
            {
                return ResourceManager.GetString("Comments_AkismetRequiresPermissionType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, could not verify that Akismet API key..
        /// </summary>
        public static string Comments_CouldNotVerifyAkismetKey
        {
            get
            {
                return ResourceManager.GetString("Comments_CouldNotVerifyAkismetKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment settings update failed..
        /// </summary>
        public static string Comments_SettingsFailed
        {
            get
            {
                return ResourceManager.GetString("Comments_SettingsFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your comment settings were successfully updated..
        /// </summary>
        public static string Comments_SettingsUpdated
        {
            get
            {
                return ResourceManager.GetString("Comments_SettingsUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment Delay.
        /// </summary>
        public static string CommentValidation_CommentDelay
        {
            get
            {
                return ResourceManager.GetString("CommentValidation_CommentDelay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; of {1} would block an IP for a really long time. Let&apos;s be reasonable..
        /// </summary>
        public static string CommentValidation_CommentDelayTooBig
        {
            get
            {
                return ResourceManager.GetString("CommentValidation_CommentDelayTooBig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should larger than {1}. You can&apos;t go back in time..
        /// </summary>
        public static string CommentValidation_CommentDelayTooSmall
        {
            get
            {
                return ResourceManager.GetString("CommentValidation_CommentDelayTooSmall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Days Till Comments Close.
        /// </summary>
        public static string CommentValidation_DaysTillClose
        {
            get
            {
                return ResourceManager.GetString("CommentValidation_DaysTillClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Length of Recent Comments to Display (Number of characters).
        /// </summary>
        public static string CommentValidation_LengthOfRecentComment
        {
            get
            {
                return ResourceManager.GetString("CommentValidation_LengthOfRecentComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number of Recent Comments to Display.
        /// </summary>
        public static string CommentValidation_RecentCommentsCount
        {
            get
            {
                return ResourceManager.GetString("CommentValidation_RecentCommentsCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ConfirmCommand was not set upon transfer..
        /// </summary>
        public static string Confirm_CommandNotSet
        {
            get
            {
                return ResourceManager.GetString("Confirm_CommandNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The archive has been processed..
        /// </summary>
        public static string EditGalleries_ArchiveProcessed
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_ArchiveProcessed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editing Image &quot;{0}&quot;.
        /// </summary>
        public static string EditGalleries_EditImage
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_EditImage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This file already exists on the server. Please provide a name for the file..
        /// </summary>
        public static string EditGalleries_FileAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_FileAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The image was successfully added to the gallery..
        /// </summary>
        public static string EditGalleries_ImageAdded
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_ImageAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An image identifier was not available, could not load your image..
        /// </summary>
        public static string EditGalleries_ImageIdentifierMissing
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_ImageIdentifierMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The image was successfully updated..
        /// </summary>
        public static string EditGalleries_ImageUpdated
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_ImageUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You must have at least one valid Gallery before working with individual images..
        /// </summary>
        public static string EditGalleries_MustHaveOneGallery
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_MustHaveOneGallery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was a baseline problem posting your entry..
        /// </summary>
        public static string EditGalleries_ProblemPosting
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_ProblemPosting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid file name for server image is required..
        /// </summary>
        public static string EditGalleries_ValidFilenameRequired
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_ValidFilenameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Viewing Gallery &quot;{0}&quot;.
        /// </summary>
        public static string EditGalleries_ViewingGallery
        {
            get
            {
                return ResourceManager.GetString("EditGalleries_ViewingGallery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You need to add a category before you can add links! Click &quot;Edit Categories&quot;.
        /// </summary>
        public static string EditLinks_NeedToAddCategoryFirst
        {
            get
            {
                return ResourceManager.GetString("EditLinks_NeedToAddCategoryFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find category id {0} in the Checkbox list which has {1} items..
        /// </summary>
        public static string EntryEditor_CouldNotFindCategoryInList
        {
            get
            {
                return ResourceManager.GetString("EntryEditor_CouldNotFindCategoryInList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Editing {0} &quot;{1}&quot;.
        /// </summary>
        public static string EntryEditor_EditingTitle
        {
            get
            {
                return ResourceManager.GetString("EntryEditor_EditingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error during Community Credits submission (your post has been saved).
        /// </summary>
        public static string EntryEditor_ErrorSendingToCommunityCredits
        {
            get
            {
                return ResourceManager.GetString("EntryEditor_ErrorSendingToCommunityCredits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There was a baseline problem updating the post categories..
        /// </summary>
        public static string EntryEditor_ProblemEditingPostCategories
        {
            get
            {
                return ResourceManager.GetString("EntryEditor_ProblemEditingPostCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string EntryList_AddComment
        {
            get
            {
                return ResourceManager.GetString("EntryList_AddComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Click To View Entry..
        /// </summary>
        public static string EntryList_ClickToView
        {
            get
            {
                return ResourceManager.GetString("EntryList_ClickToView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  Comments.
        /// </summary>
        public static string EntryList_CommentsPlural
        {
            get
            {
                return ResourceManager.GetString("EntryList_CommentsPlural", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One Comment.
        /// </summary>
        public static string EntryList_OneComment
        {
            get
            {
                return ResourceManager.GetString("EntryList_OneComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permanent link to this post.
        /// </summary>
        public static string EntryList_PermanentLink
        {
            get
            {
                return ResourceManager.GetString("EntryList_PermanentLink", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View and Add Comments.
        /// </summary>
        public static string EntryList_ViewAndAddComments
        {
            get
            {
                return ResourceManager.GetString("EntryList_ViewAndAddComments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No error message available..
        /// </summary>
        public static string ErrorPage_NoErrorMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorPage_NoErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing was selected as spam..
        /// </summary>
        public static string Feedback_NothingFlaggedAsSpam
        {
            get
            {
                return ResourceManager.GetString("Feedback_NothingFlaggedAsSpam", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing was selected to be approved..
        /// </summary>
        public static string Feedback_NothingToApprove
        {
            get
            {
                return ResourceManager.GetString("Feedback_NothingToApprove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing was selected to be deleted..
        /// </summary>
        public static string Feedback_NothingToDelete
        {
            get
            {
                return ResourceManager.GetString("Feedback_NothingToDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nothing was selected to be destroyed..
        /// </summary>
        public static string Feedback_NothingToDestroy
        {
            get
            {
                return ResourceManager.GetString("Feedback_NothingToDestroy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your new password.
        /// </summary>
        public static string ForgotPassword_NewPassword
        {
            get
            {
                return ResourceManager.GetString("ForgotPassword_NewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password was reset and sent to your email address..
        /// </summary>
        public static string ForgotPassword_NewPasswordSent
        {
            get
            {
                return ResourceManager.GetString("ForgotPassword_NewPasswordSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the username and email provided did not match our records.
        /// </summary>
        public static string ForgotPassword_UsernameAndPasswordDoNotMatch
        {
            get
            {
                return ResourceManager.GetString("ForgotPassword_UsernameAndPasswordDoNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, but forgot password does not work for Host admins. Please read &lt;a href=&quot;http://subtextproject.com/Home/FAQ/tabid/113/Default.aspx&quot; title=&quot;Subtext FAQ&quot;&gt;the FAQ&lt;/a&gt; to reset your password..
        /// </summary>
        public static string ForgotPasswordMaster_DoesNotWorkForHostAdmins
        {
            get
            {
                return ResourceManager.GetString("ForgotPasswordMaster_DoesNotWorkForHostAdmins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve been told that you forgot your password. Here it is
        ///  {0}.
        /// </summary>
        public static string ForgotPaswword_HereIsNewPassword
        {
            get
            {
                return ResourceManager.GetString("ForgotPaswword_HereIsNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rebuild of full text index completed.
        /// </summary>
        public static string FullTextSearch_ReindexingCompleted
        {
            get
            {
                return ResourceManager.GetString("FullTextSearch_ReindexingCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rebuild of full text index completed with errors:&lt;br&gt;&lt;ul&gt;{0}&lt;/ul&gt;.
        /// </summary>
        public static string FullTextSearch_ReindexingCompletedWithErrorsFormat
        {
            get
            {
                return ResourceManager.GetString("FullTextSearch_ReindexingCompletedWithErrorsFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rebuild of full text index failed.
        /// </summary>
        public static string FullTextSearch_ReindexingFailed
        {
            get
            {
                return ResourceManager.GetString("FullTextSearch_ReindexingFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Group Created..
        /// </summary>
        public static string GroupsEditor_BlogGroupCreated
        {
            get
            {
                return ResourceManager.GetString("GroupsEditor_BlogGroupCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Group Saved..
        /// </summary>
        public static string GroupsEditor_BlogGroupSaved
        {
            get
            {
                return ResourceManager.GetString("GroupsEditor_BlogGroupSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Use this page to manage the blogs groups for this server. 
        ///For more information on configuring blogs, see the &lt;a href=&apos;http://www.subtextproject.com/Home/Docs/Configuration/tabid/112/Default.aspx&apos; target=&apos;_blank&apos;&gt;configuration docs&lt;/a&gt; (opens a new window).
        ///&lt;/p&gt;.
        /// </summary>
        public static string GroupsEditor_HelpTip
        {
            get
            {
                return ResourceManager.GetString("GroupsEditor_HelpTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Group Update Cancelled. Nothing to see here..
        /// </summary>
        public static string GroupsEditor_UpdateCancelled
        {
            get
            {
                return ResourceManager.GetString("GroupsEditor_UpdateCancelled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You need to check the &quot;Clear Content&quot; checkbox to continue..
        /// </summary>
        public static string ImportExport_CheckContinueToClearContent
        {
            get
            {
                return ResourceManager.GetString("ImportExport_CheckContinueToClearContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Success! The content has been obliterated!.
        /// </summary>
        public static string ImportExport_ContentObliterated
        {
            get
            {
                return ResourceManager.GetString("ImportExport_ContentObliterated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import of BlogML file failed..
        /// </summary>
        public static string ImportExport_ImportFailed
        {
            get
            {
                return ResourceManager.GetString("ImportExport_ImportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The BlogML file was successfully imported!.
        /// </summary>
        public static string ImportExport_ImportSuccess
        {
            get
            {
                return ResourceManager.GetString("ImportExport_ImportSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file you specified does not appear to be a valid BlogML file..
        /// </summary>
        public static string ImportExport_InvalidBlogMLFile
        {
            get
            {
                return ResourceManager.GetString("ImportExport_InvalidBlogMLFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CategoryType was not set.
        /// </summary>
        public static string InvalidOperation_CategoryTypeNotSet
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_CategoryTypeNotSet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, but we cannot accept this comment..
        /// </summary>
        public static string InvalidOperation_CommentNotValid
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_CommentNotValid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update failed, could not located either the item Title or IsActive.
        /// </summary>
        public static string InvalidOperation_EditCategoriesControlsNotFound
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_EditCategoriesControlsNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Image not defined..
        /// </summary>
        public static string InvalidOperation_ImageUndefined
        {
            get
            {
                return ResourceManager.GetString("InvalidOperation_ImageUndefined", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Label_Activate
        {
            get
            {
                return ResourceManager.GetString("Label_Activate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Adds.
        /// </summary>
        public static string Label_Adds
        {
            get
            {
                return ResourceManager.GetString("Label_Adds", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Label_Article
        {
            get
            {
                return ResourceManager.GetString("Label_Article", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Label_Articles
        {
            get
            {
                return ResourceManager.GetString("Label_Articles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose....
        /// </summary>
        public static string Label_Choose
        {
            get
            {
                return ResourceManager.GetString("Label_Choose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string Label_Deactivate
        {
            get
            {
                return ResourceManager.GetString("Label_Deactivate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Categories.
        /// </summary>
        public static string Label_EditCategories
        {
            get
            {
                return ResourceManager.GetString("Label_EditCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Blog Posts.
        /// </summary>
        public static string Label_Entries
        {
            get
            {
                return ResourceManager.GetString("Label_Entries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Label_Errors
        {
            get
            {
                return ResourceManager.GetString("Label_Errors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to images.
        /// </summary>
        public static string Label_Images
        {
            get
            {
                return ResourceManager.GetString("Label_Images", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Article.
        /// </summary>
        public static string Label_NewArticle
        {
            get
            {
                return ResourceManager.GetString("Label_NewArticle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Blog Group.
        /// </summary>
        public static string Label_NewBlogGroup
        {
            get
            {
                return ResourceManager.GetString("Label_NewBlogGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Post.
        /// </summary>
        public static string Label_NewPost
        {
            get
            {
                return ResourceManager.GetString("Label_NewPost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Label_Other
        {
            get
            {
                return ResourceManager.GetString("Label_Other", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Label_Post
        {
            get
            {
                return ResourceManager.GetString("Label_Post", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Label_Posts
        {
            get
            {
                return ResourceManager.GetString("Label_Posts", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rebuild All Tags.
        /// </summary>
        public static string Label_RebuildAllTags
        {
            get
            {
                return ResourceManager.GetString("Label_RebuildAllTags", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Label_Updates
        {
            get
            {
                return ResourceManager.GetString("Label_Updates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Label_View
        {
            get
            {
                return ResourceManager.GetString("Label_View", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Viewing.
        /// </summary>
        public static string Label_Viewing
        {
            get
            {
                return ResourceManager.GetString("Label_Viewing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Subscribe to {0}.
        /// </summary>
        public static string LinkPage_Subscribe
        {
            get
            {
                return ResourceManager.GetString("LinkPage_Subscribe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Authentication failed.
        /// </summary>
        public static string Login_AuthenticationFailed
        {
            get
            {
                return ResourceManager.GetString("Login_AuthenticationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to That&amp;#8217;s not it.
        /// </summary>
        public static string Login_Failed
        {
            get
            {
                return ResourceManager.GetString("Login_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Categories updated successfully..
        /// </summary>
        public static string Message_CategoriesUpdatedSuccessful
        {
            get
            {
                return ResourceManager.GetString("Message_CategoriesUpdatedSuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; was added..
        /// </summary>
        public static string Message_CategoryAdded
        {
            get
            {
                return ResourceManager.GetString("Message_CategoryAdded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A category must have a title.
        /// </summary>
        public static string Message_CategoryMustHaveTitle
        {
            get
            {
                return ResourceManager.GetString("Message_CategoryMustHaveTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category &quot;{0}&quot; was updated..
        /// </summary>
        public static string Message_CategoryUpdated
        {
            get
            {
                return ResourceManager.GetString("Message_CategoryUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category Update failed..
        /// </summary>
        public static string Message_CategoryUpdateFailed
        {
            get
            {
                return ResourceManager.GetString("Message_CategoryUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this form has expired. Please try again..
        /// </summary>
        public static string Message_FormExpired
        {
            get
            {
                return ResourceManager.GetString("Message_FormExpired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} The error message related to this problem was as follows: {1}.
        /// </summary>
        public static string Message_GenericError
        {
            get
            {
                return ResourceManager.GetString("Message_GenericError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct word.
        /// </summary>
        public static string Message_PleaseEnterCorrectWord
        {
            get
            {
                return ResourceManager.GetString("Message_PleaseEnterCorrectWord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Posted successfully..
        /// </summary>
        public static string Message_PostedSuccessful
        {
            get
            {
                return ResourceManager.GetString("Message_PostedSuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Post operation failed..
        /// </summary>
        public static string Message_PostOperationFailed
        {
            get
            {
                return ResourceManager.GetString("Message_PostOperationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Darn! An unexpected error occurred.  Not sure what happened. Sorry..
        /// </summary>
        public static string Message_UnexpectedError
        {
            get
            {
                return ResourceManager.GetString("Message_UnexpectedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Updated successfully..
        /// </summary>
        public static string Message_UpdateSuccessful
        {
            get
            {
                return ResourceManager.GetString("Message_UpdateSuccessful", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid positive number for the field &quot;{0}&quot;.
        /// </summary>
        public static string Message_ValueMustBePositive
        {
            get
            {
                return ResourceManager.GetString("Message_ValueMustBePositive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should be less than or equal to {1}.
        /// </summary>
        public static string Message_ValueTooBig
        {
            get
            {
                return ResourceManager.GetString("Message_ValueTooBig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; should be larger than or equal to {1}.
        /// </summary>
        public static string Message_ValueTooSmall
        {
            get
            {
                return ResourceManager.GetString("Message_ValueTooSmall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You will lose any unsaved content.
        /// </summary>
        public static string Message_YouWillLoseUnsavedContent
        {
            get
            {
                return ResourceManager.GetString("Message_YouWillLoseUnsavedContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thanks for your comment!.
        /// </summary>
        public static string PostComment_ThanksForComment
        {
            get
            {
                return ResourceManager.GetString("PostComment_ThanksForComment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to That page is forbidden..
        /// </summary>
        public static string Security_PageForbidden
        {
            get
            {
                return ResourceManager.GetString("Security_PageForbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your password can not be updated.
        /// </summary>
        public static string Security_PasswordNotUpdated
        {
            get
            {
                return ResourceManager.GetString("Security_PasswordNotUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated.
        /// </summary>
        public static string Security_PasswordUpdated
        {
            get
            {
                return ResourceManager.GetString("Security_PasswordUpdated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to  (mobile ready).
        /// </summary>
        public static string Skins_MobileReady
        {
            get
            {
                return ResourceManager.GetString("Skins_MobileReady", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skin Saved!.
        /// </summary>
        public static string Skins_SkinSaved
        {
            get
            {
                return ResourceManager.GetString("Skins_SkinSaved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There are {0} entries for the tag &lt;em&gt;{1}&lt;/em&gt;.
        /// </summary>
        public static string TagEntryList_NoEntriesForTag
        {
            get
            {
                return ResourceManager.GetString("TagEntryList_NoEntriesForTag", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Uh oh. Something went wrong with the installation.&lt;/p&gt;.
        /// </summary>
        public static string Upgrade_SomethingWentWrongWithInstall
        {
            get
            {
                return ResourceManager.GetString("Upgrade_SomethingWentWrongWithInstall", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;error&quot;&gt;The database user specified in web.config does not have enough 
        ///permission to perform the installation.  Please give the user database owner (dbo) rights and try again. 
        ///You may remove them later.&lt;/p&gt;.
        /// </summary>
        public static string Upgrade_UserDoesNotHavePermission
        {
            get
            {
                return ResourceManager.GetString("Upgrade_UserDoesNotHavePermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit this entry..
        /// </summary>
        public static string ViewPost_EditThisEntry
        {
            get
            {
                return ResourceManager.GetString("ViewPost_EditThisEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;The entry could not be found or has been removed&lt;/strong&gt;&lt;/p&gt;.
        /// </summary>
        public static string ViewPost_EntryNotFound
        {
            get
            {
                return ResourceManager.GetString("ViewPost_EntryNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CaptchaExpired Exception thrown..
        /// </summary>
        public static string Warning_CaptchaExpired
        {
            get
            {
                return ResourceManager.GetString("Warning_CaptchaExpired", resourceCulture);
            }
        }
    }
}
