//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.HostAdmin.UserControls {
    
    public partial class GroupsEditor {
        protected Subtext.Web.Admin.WebUI.MessagePanel messagePanel;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel pnlResults;
        protected System.Web.UI.WebControls.CheckBox chkShowInactive;
        protected System.Web.UI.WebControls.Repeater rprGroupsList;
        protected System.Web.UI.HtmlControls.HtmlGenericControl lblNoMessages;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel pnlEdit;
        protected Subtext.Web.Controls.HelpToolTip blogEditorHelp;
        protected System.Web.UI.HtmlControls.HtmlImage Img3;
        protected System.Web.UI.WebControls.HiddenField hfActive;
        protected System.Web.UI.WebControls.TextBox txtTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox txtDisplayOrder;
        protected System.Web.UI.WebControls.RangeValidator RangeValidator1;
        protected System.Web.UI.WebControls.TextBox txtDescription;
        protected System.Web.UI.WebControls.Button btnCancel;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
