//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.HostAdmin {
    
    public partial class Step02_GatherInfo {
        protected System.Web.UI.WebControls.Literal ltlErrorMessage;
        protected System.Web.UI.WebControls.PlaceHolder plcImportInformation;
        protected System.Web.UI.WebControls.Button btnNext;
        protected System.Web.UI.HtmlControls.HtmlGenericControl paraBeginImportText;
        protected System.Web.UI.WebControls.Button btnBeginImport;
    }
}
