//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.WebUI {
    
    public partial class AdminPageTemplate {
        protected Subtext.Web.Controls.ScriptTag NiceForms;
        protected Subtext.Web.Controls.ScriptTag HelptipJs;
        protected Subtext.Web.Controls.ScriptTag AdminJs;
        protected Subtext.Web.Controls.ScriptTag tableEffectsJS;
        protected System.Web.UI.HtmlControls.HtmlLink commonLayoutCss;
        protected System.Web.UI.HtmlControls.HtmlLink commonStyleCss;
        protected Subtext.Web.Admin.WebUI.HeaderLink HelptipCss;
        protected Subtext.Web.Admin.WebUI.HeaderLink adminCss;
        protected Subtext.Web.Admin.WebUI.HeaderLink NiceFormsStyle;
        protected System.Web.UI.HtmlControls.HtmlGenericControl AdminSection;
        protected System.Web.UI.HtmlControls.HtmlForm frmMain;
        protected System.Web.UI.WebControls.Literal LoggedInUser;
        protected System.Web.UI.WebControls.LinkButton LogoutLink;
        protected System.Web.UI.WebControls.HyperLink BlogTitleLink;
        protected System.Web.UI.WebControls.ContentPlaceHolder actionsHeading;
        protected System.Web.UI.HtmlControls.HtmlGenericControl galleryTab;
        protected Subtext.Web.Admin.WebUI.BreadCrumbs breadCrumbs;
        protected Subtext.Web.Admin.WebUI.LinkList LinksActions;
        protected System.Web.UI.WebControls.ContentPlaceHolder categoryListHeading;
        protected System.Web.UI.WebControls.ContentPlaceHolder categoryListLinks;
        protected System.Web.UI.WebControls.ContentPlaceHolder pageContent;
    }
}
