//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web {
    
    public partial class _default {
        protected System.Web.UI.WebControls.Literal TitleTag;
        protected System.Web.UI.WebControls.Literal Style;
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.HyperLink TitleLink;
        protected System.Web.UI.WebControls.HyperLink HyperLink1;
        protected System.Web.UI.WebControls.HyperLink OpmlLink;
        protected System.Web.UI.WebControls.HyperLink RssLink;
        protected System.Web.UI.WebControls.HyperLink Hyperlink4;
        protected System.Web.UI.WebControls.HyperLink Hyperlink5;
        protected System.Web.UI.WebControls.Literal BlogCount;
        protected System.Web.UI.WebControls.Literal PostCount;
        protected System.Web.UI.WebControls.Literal StoryCount;
        protected System.Web.UI.WebControls.Literal CommentCount;
        protected System.Web.UI.WebControls.Literal PingtrackCount;
        protected System.Web.UI.WebControls.Repeater Bloggers;
        protected System.Web.UI.WebControls.Repeater RecentPosts;
    }
}
