//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1378.
// 
#pragma warning disable 1591

namespace Subtext.Framework.com.community_credit.www {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AffiliateServicesSoap", Namespace="http://www.community-credit.com/")]
    public partial class AffiliateServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddNewsgroupItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateFutureCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutoSubmitBlogOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddNewsgroupCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCommunityCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopEarnersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SpreadTheWordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDemographicsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopEarnersByDateRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback PointCategoriesAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEarnersByDateRangeAndEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendConfirmationEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendWelcomeEmailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AffiliateServices() {
            this.Url = global::Subtext.Framework.Properties.Settings.Default.Subtext_Framework_com_community_credit_www_AffiliateServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddNewsgroupItemCompletedEventHandler AddNewsgroupItemCompleted;
        
        /// <remarks/>
        public event GenerateFutureCreditCompletedEventHandler GenerateFutureCreditCompleted;
        
        /// <remarks/>
        public event AutoSubmitBlogCompletedEventHandler AutoSubmitBlogCompleted;
        
        /// <remarks/>
        public event AddNewsgroupCreditCompletedEventHandler AddNewsgroupCreditCompleted;
        
        /// <remarks/>
        public event AddCommunityCreditCompletedEventHandler AddCommunityCreditCompleted;
        
        /// <remarks/>
        public event GetTopEarnersCompletedEventHandler GetTopEarnersCompleted;
        
        /// <remarks/>
        public event SpreadTheWordCompletedEventHandler SpreadTheWordCompleted;
        
        /// <remarks/>
        public event GetDemographicsCompletedEventHandler GetDemographicsCompleted;
        
        /// <remarks/>
        public event GetTopEarnersByDateRangeCompletedEventHandler GetTopEarnersByDateRangeCompleted;
        
        /// <remarks/>
        public event PointCategoriesAllCompletedEventHandler PointCategoriesAllCompleted;
        
        /// <remarks/>
        public event GetEarnersByDateRangeAndEmailCompletedEventHandler GetEarnersByDateRangeAndEmailCompleted;
        
        /// <remarks/>
        public event SendConfirmationEmailCompletedEventHandler SendConfirmationEmailCompleted;
        
        /// <remarks/>
        public event SendWelcomeEmailCompletedEventHandler SendWelcomeEmailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/AddNewsgroupItem", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddNewsgroupItem(string MessageId, string ReferenceId, string NewsgroupID, string User, string Subject, string Message, string NewsgroupDate, string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("AddNewsgroupItem", new object[] {
                        MessageId,
                        ReferenceId,
                        NewsgroupID,
                        User,
                        Subject,
                        Message,
                        NewsgroupDate,
                        AffiliateCode,
                        AffiliateKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewsgroupItemAsync(string MessageId, string ReferenceId, string NewsgroupID, string User, string Subject, string Message, string NewsgroupDate, string AffiliateCode, string AffiliateKey) {
            this.AddNewsgroupItemAsync(MessageId, ReferenceId, NewsgroupID, User, Subject, Message, NewsgroupDate, AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void AddNewsgroupItemAsync(string MessageId, string ReferenceId, string NewsgroupID, string User, string Subject, string Message, string NewsgroupDate, string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.AddNewsgroupItemOperationCompleted == null)) {
                this.AddNewsgroupItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewsgroupItemOperationCompleted);
            }
            this.InvokeAsync("AddNewsgroupItem", new object[] {
                        MessageId,
                        ReferenceId,
                        NewsgroupID,
                        User,
                        Subject,
                        Message,
                        NewsgroupDate,
                        AffiliateCode,
                        AffiliateKey}, this.AddNewsgroupItemOperationCompleted, userState);
        }
        
        private void OnAddNewsgroupItemOperationCompleted(object arg) {
            if ((this.AddNewsgroupItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewsgroupItemCompleted(this, new AddNewsgroupItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/GenerateFutureCredit", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateFutureCredit(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("GenerateFutureCredit", new object[] {
                        EarnerEmail,
                        EarnerFirstName,
                        EarnerLastName,
                        TaskDescription,
                        ReferenceURL,
                        PointCategory,
                        AffiliateCode,
                        AffiliateKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerateFutureCreditAsync(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, string AffiliateCode, string AffiliateKey) {
            this.GenerateFutureCreditAsync(EarnerEmail, EarnerFirstName, EarnerLastName, TaskDescription, ReferenceURL, PointCategory, AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void GenerateFutureCreditAsync(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.GenerateFutureCreditOperationCompleted == null)) {
                this.GenerateFutureCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateFutureCreditOperationCompleted);
            }
            this.InvokeAsync("GenerateFutureCredit", new object[] {
                        EarnerEmail,
                        EarnerFirstName,
                        EarnerLastName,
                        TaskDescription,
                        ReferenceURL,
                        PointCategory,
                        AffiliateCode,
                        AffiliateKey}, this.GenerateFutureCreditOperationCompleted, userState);
        }
        
        private void OnGenerateFutureCreditOperationCompleted(object arg) {
            if ((this.GenerateFutureCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateFutureCreditCompleted(this, new GenerateFutureCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/AutoSubmitBlog", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AutoSubmitBlog(string RSSFeedURL, string AffiliateCode, string AffiliateKey, string BlogURL, string BlogTitle, System.DateTime BlogDate) {
            object[] results = this.Invoke("AutoSubmitBlog", new object[] {
                        RSSFeedURL,
                        AffiliateCode,
                        AffiliateKey,
                        BlogURL,
                        BlogTitle,
                        BlogDate});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AutoSubmitBlogAsync(string RSSFeedURL, string AffiliateCode, string AffiliateKey, string BlogURL, string BlogTitle, System.DateTime BlogDate) {
            this.AutoSubmitBlogAsync(RSSFeedURL, AffiliateCode, AffiliateKey, BlogURL, BlogTitle, BlogDate, null);
        }
        
        /// <remarks/>
        public void AutoSubmitBlogAsync(string RSSFeedURL, string AffiliateCode, string AffiliateKey, string BlogURL, string BlogTitle, System.DateTime BlogDate, object userState) {
            if ((this.AutoSubmitBlogOperationCompleted == null)) {
                this.AutoSubmitBlogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutoSubmitBlogOperationCompleted);
            }
            this.InvokeAsync("AutoSubmitBlog", new object[] {
                        RSSFeedURL,
                        AffiliateCode,
                        AffiliateKey,
                        BlogURL,
                        BlogTitle,
                        BlogDate}, this.AutoSubmitBlogOperationCompleted, userState);
        }
        
        private void OnAutoSubmitBlogOperationCompleted(object arg) {
            if ((this.AutoSubmitBlogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutoSubmitBlogCompleted(this, new AutoSubmitBlogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/AddNewsgroupCredit", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddNewsgroupCredit(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, System.DateTime EarnedDate, string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("AddNewsgroupCredit", new object[] {
                        EarnerEmail,
                        EarnerFirstName,
                        EarnerLastName,
                        TaskDescription,
                        ReferenceURL,
                        PointCategory,
                        EarnedDate,
                        AffiliateCode,
                        AffiliateKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewsgroupCreditAsync(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, System.DateTime EarnedDate, string AffiliateCode, string AffiliateKey) {
            this.AddNewsgroupCreditAsync(EarnerEmail, EarnerFirstName, EarnerLastName, TaskDescription, ReferenceURL, PointCategory, EarnedDate, AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void AddNewsgroupCreditAsync(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, System.DateTime EarnedDate, string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.AddNewsgroupCreditOperationCompleted == null)) {
                this.AddNewsgroupCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewsgroupCreditOperationCompleted);
            }
            this.InvokeAsync("AddNewsgroupCredit", new object[] {
                        EarnerEmail,
                        EarnerFirstName,
                        EarnerLastName,
                        TaskDescription,
                        ReferenceURL,
                        PointCategory,
                        EarnedDate,
                        AffiliateCode,
                        AffiliateKey}, this.AddNewsgroupCreditOperationCompleted, userState);
        }
        
        private void OnAddNewsgroupCreditOperationCompleted(object arg) {
            if ((this.AddNewsgroupCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewsgroupCreditCompleted(this, new AddNewsgroupCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/AddCommunityCredit", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddCommunityCredit(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("AddCommunityCredit", new object[] {
                        EarnerEmail,
                        EarnerFirstName,
                        EarnerLastName,
                        TaskDescription,
                        ReferenceURL,
                        PointCategory,
                        AffiliateCode,
                        AffiliateKey});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddCommunityCreditAsync(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, string AffiliateCode, string AffiliateKey) {
            this.AddCommunityCreditAsync(EarnerEmail, EarnerFirstName, EarnerLastName, TaskDescription, ReferenceURL, PointCategory, AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void AddCommunityCreditAsync(string EarnerEmail, string EarnerFirstName, string EarnerLastName, string TaskDescription, string ReferenceURL, string PointCategory, string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.AddCommunityCreditOperationCompleted == null)) {
                this.AddCommunityCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCommunityCreditOperationCompleted);
            }
            this.InvokeAsync("AddCommunityCredit", new object[] {
                        EarnerEmail,
                        EarnerFirstName,
                        EarnerLastName,
                        TaskDescription,
                        ReferenceURL,
                        PointCategory,
                        AffiliateCode,
                        AffiliateKey}, this.AddCommunityCreditOperationCompleted, userState);
        }
        
        private void OnAddCommunityCreditOperationCompleted(object arg) {
            if ((this.AddCommunityCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCommunityCreditCompleted(this, new AddCommunityCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/GetTopEarners", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTopEarners(string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("GetTopEarners", new object[] {
                        AffiliateCode,
                        AffiliateKey});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopEarnersAsync(string AffiliateCode, string AffiliateKey) {
            this.GetTopEarnersAsync(AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void GetTopEarnersAsync(string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.GetTopEarnersOperationCompleted == null)) {
                this.GetTopEarnersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopEarnersOperationCompleted);
            }
            this.InvokeAsync("GetTopEarners", new object[] {
                        AffiliateCode,
                        AffiliateKey}, this.GetTopEarnersOperationCompleted, userState);
        }
        
        private void OnGetTopEarnersOperationCompleted(object arg) {
            if ((this.GetTopEarnersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopEarnersCompleted(this, new GetTopEarnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/SpreadTheWord", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SpreadTheWord(string AffiliateCode, string AffiliateKey, string FromName, string ToEmailAddress, string FirstName, string LastName) {
            object[] results = this.Invoke("SpreadTheWord", new object[] {
                        AffiliateCode,
                        AffiliateKey,
                        FromName,
                        ToEmailAddress,
                        FirstName,
                        LastName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SpreadTheWordAsync(string AffiliateCode, string AffiliateKey, string FromName, string ToEmailAddress, string FirstName, string LastName) {
            this.SpreadTheWordAsync(AffiliateCode, AffiliateKey, FromName, ToEmailAddress, FirstName, LastName, null);
        }
        
        /// <remarks/>
        public void SpreadTheWordAsync(string AffiliateCode, string AffiliateKey, string FromName, string ToEmailAddress, string FirstName, string LastName, object userState) {
            if ((this.SpreadTheWordOperationCompleted == null)) {
                this.SpreadTheWordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSpreadTheWordOperationCompleted);
            }
            this.InvokeAsync("SpreadTheWord", new object[] {
                        AffiliateCode,
                        AffiliateKey,
                        FromName,
                        ToEmailAddress,
                        FirstName,
                        LastName}, this.SpreadTheWordOperationCompleted, userState);
        }
        
        private void OnSpreadTheWordOperationCompleted(object arg) {
            if ((this.SpreadTheWordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SpreadTheWordCompleted(this, new SpreadTheWordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/GetDemographics", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDemographics(string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("GetDemographics", new object[] {
                        AffiliateCode,
                        AffiliateKey});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDemographicsAsync(string AffiliateCode, string AffiliateKey) {
            this.GetDemographicsAsync(AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void GetDemographicsAsync(string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.GetDemographicsOperationCompleted == null)) {
                this.GetDemographicsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemographicsOperationCompleted);
            }
            this.InvokeAsync("GetDemographics", new object[] {
                        AffiliateCode,
                        AffiliateKey}, this.GetDemographicsOperationCompleted, userState);
        }
        
        private void OnGetDemographicsOperationCompleted(object arg) {
            if ((this.GetDemographicsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemographicsCompleted(this, new GetDemographicsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/GetTopEarnersByDateRange", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTopEarnersByDateRange(string StartDate, string EndDate, string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("GetTopEarnersByDateRange", new object[] {
                        StartDate,
                        EndDate,
                        AffiliateCode,
                        AffiliateKey});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopEarnersByDateRangeAsync(string StartDate, string EndDate, string AffiliateCode, string AffiliateKey) {
            this.GetTopEarnersByDateRangeAsync(StartDate, EndDate, AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void GetTopEarnersByDateRangeAsync(string StartDate, string EndDate, string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.GetTopEarnersByDateRangeOperationCompleted == null)) {
                this.GetTopEarnersByDateRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopEarnersByDateRangeOperationCompleted);
            }
            this.InvokeAsync("GetTopEarnersByDateRange", new object[] {
                        StartDate,
                        EndDate,
                        AffiliateCode,
                        AffiliateKey}, this.GetTopEarnersByDateRangeOperationCompleted, userState);
        }
        
        private void OnGetTopEarnersByDateRangeOperationCompleted(object arg) {
            if ((this.GetTopEarnersByDateRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopEarnersByDateRangeCompleted(this, new GetTopEarnersByDateRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/PointCategoriesAll", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet PointCategoriesAll(string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("PointCategoriesAll", new object[] {
                        AffiliateCode,
                        AffiliateKey});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void PointCategoriesAllAsync(string AffiliateCode, string AffiliateKey) {
            this.PointCategoriesAllAsync(AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void PointCategoriesAllAsync(string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.PointCategoriesAllOperationCompleted == null)) {
                this.PointCategoriesAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPointCategoriesAllOperationCompleted);
            }
            this.InvokeAsync("PointCategoriesAll", new object[] {
                        AffiliateCode,
                        AffiliateKey}, this.PointCategoriesAllOperationCompleted, userState);
        }
        
        private void OnPointCategoriesAllOperationCompleted(object arg) {
            if ((this.PointCategoriesAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PointCategoriesAllCompleted(this, new PointCategoriesAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/GetEarnersByDateRangeAndEmail", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetEarnersByDateRangeAndEmail(string Email, string StartDate, string EndDate, string AffiliateCode, string AffiliateKey) {
            object[] results = this.Invoke("GetEarnersByDateRangeAndEmail", new object[] {
                        Email,
                        StartDate,
                        EndDate,
                        AffiliateCode,
                        AffiliateKey});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetEarnersByDateRangeAndEmailAsync(string Email, string StartDate, string EndDate, string AffiliateCode, string AffiliateKey) {
            this.GetEarnersByDateRangeAndEmailAsync(Email, StartDate, EndDate, AffiliateCode, AffiliateKey, null);
        }
        
        /// <remarks/>
        public void GetEarnersByDateRangeAndEmailAsync(string Email, string StartDate, string EndDate, string AffiliateCode, string AffiliateKey, object userState) {
            if ((this.GetEarnersByDateRangeAndEmailOperationCompleted == null)) {
                this.GetEarnersByDateRangeAndEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEarnersByDateRangeAndEmailOperationCompleted);
            }
            this.InvokeAsync("GetEarnersByDateRangeAndEmail", new object[] {
                        Email,
                        StartDate,
                        EndDate,
                        AffiliateCode,
                        AffiliateKey}, this.GetEarnersByDateRangeAndEmailOperationCompleted, userState);
        }
        
        private void OnGetEarnersByDateRangeAndEmailOperationCompleted(object arg) {
            if ((this.GetEarnersByDateRangeAndEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEarnersByDateRangeAndEmailCompleted(this, new GetEarnersByDateRangeAndEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/SendConfirmationEmail", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendConfirmationEmail(string EmailAddress, string FirstName) {
            this.Invoke("SendConfirmationEmail", new object[] {
                        EmailAddress,
                        FirstName});
        }
        
        /// <remarks/>
        public void SendConfirmationEmailAsync(string EmailAddress, string FirstName) {
            this.SendConfirmationEmailAsync(EmailAddress, FirstName, null);
        }
        
        /// <remarks/>
        public void SendConfirmationEmailAsync(string EmailAddress, string FirstName, object userState) {
            if ((this.SendConfirmationEmailOperationCompleted == null)) {
                this.SendConfirmationEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendConfirmationEmailOperationCompleted);
            }
            this.InvokeAsync("SendConfirmationEmail", new object[] {
                        EmailAddress,
                        FirstName}, this.SendConfirmationEmailOperationCompleted, userState);
        }
        
        private void OnSendConfirmationEmailOperationCompleted(object arg) {
            if ((this.SendConfirmationEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendConfirmationEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.community-credit.com/SendWelcomeEmail", RequestNamespace="http://www.community-credit.com/", ResponseNamespace="http://www.community-credit.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SendWelcomeEmail(string Source, string strTo, string FirstName, string strPassword, string strCommunities, string strPasswordType) {
            this.Invoke("SendWelcomeEmail", new object[] {
                        Source,
                        strTo,
                        FirstName,
                        strPassword,
                        strCommunities,
                        strPasswordType});
        }
        
        /// <remarks/>
        public void SendWelcomeEmailAsync(string Source, string strTo, string FirstName, string strPassword, string strCommunities, string strPasswordType) {
            this.SendWelcomeEmailAsync(Source, strTo, FirstName, strPassword, strCommunities, strPasswordType, null);
        }
        
        /// <remarks/>
        public void SendWelcomeEmailAsync(string Source, string strTo, string FirstName, string strPassword, string strCommunities, string strPasswordType, object userState) {
            if ((this.SendWelcomeEmailOperationCompleted == null)) {
                this.SendWelcomeEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendWelcomeEmailOperationCompleted);
            }
            this.InvokeAsync("SendWelcomeEmail", new object[] {
                        Source,
                        strTo,
                        FirstName,
                        strPassword,
                        strCommunities,
                        strPasswordType}, this.SendWelcomeEmailOperationCompleted, userState);
        }
        
        private void OnSendWelcomeEmailOperationCompleted(object arg) {
            if ((this.SendWelcomeEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendWelcomeEmailCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void AddNewsgroupItemCompletedEventHandler(object sender, AddNewsgroupItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewsgroupItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewsgroupItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void GenerateFutureCreditCompletedEventHandler(object sender, GenerateFutureCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateFutureCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateFutureCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void AutoSubmitBlogCompletedEventHandler(object sender, AutoSubmitBlogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutoSubmitBlogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutoSubmitBlogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void AddNewsgroupCreditCompletedEventHandler(object sender, AddNewsgroupCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewsgroupCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewsgroupCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void AddCommunityCreditCompletedEventHandler(object sender, AddCommunityCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCommunityCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCommunityCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void GetTopEarnersCompletedEventHandler(object sender, GetTopEarnersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopEarnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopEarnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void SpreadTheWordCompletedEventHandler(object sender, SpreadTheWordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SpreadTheWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SpreadTheWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void GetDemographicsCompletedEventHandler(object sender, GetDemographicsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemographicsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDemographicsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void GetTopEarnersByDateRangeCompletedEventHandler(object sender, GetTopEarnersByDateRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopEarnersByDateRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopEarnersByDateRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void PointCategoriesAllCompletedEventHandler(object sender, PointCategoriesAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PointCategoriesAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PointCategoriesAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void GetEarnersByDateRangeAndEmailCompletedEventHandler(object sender, GetEarnersByDateRangeAndEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEarnersByDateRangeAndEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEarnersByDateRangeAndEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void SendConfirmationEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1378")]
    public delegate void SendWelcomeEmailCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591