//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.HostAdmin {
    
    public partial class ChangePassword {
        protected System.Web.UI.WebControls.Label lblSuccess;
        protected System.Web.UI.WebControls.ValidationSummary validationSummary;
        protected System.Web.UI.WebControls.RequiredFieldValidator vldCurrentPassword;
        protected System.Web.UI.WebControls.CustomValidator vldCurrent;
        protected System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected System.Web.UI.WebControls.RequiredFieldValidator vldNewPassword;
        protected System.Web.UI.WebControls.TextBox txtNewPassword;
        protected System.Web.UI.WebControls.RequiredFieldValidator vldConfirmPassword;
        protected System.Web.UI.WebControls.CompareValidator vldComparePasswords;
        protected System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected System.Web.UI.WebControls.Button btnSave;
    }
}
