//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.HostAdmin {
    
    public partial class Login {
        protected Subtext.Web.Controls.StyleTag SystemStyle;
        protected System.Web.UI.HtmlControls.HtmlForm frmLogin;
        protected System.Web.UI.WebControls.Login loginControl;
    }
}
