//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class Comments {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Edit;
        protected System.Web.UI.WebControls.CheckBox chkEnableComments;
        protected Subtext.Web.Controls.HelpToolTip HelpToolTip1;
        protected System.Web.UI.WebControls.CheckBox chkEnableTrackbacks;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip5;
        protected System.Web.UI.WebControls.CheckBox chkCoCommentEnabled;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip6;
        protected Subtext.Web.Controls.HelpToolTip hlpAkismet;
        protected System.Web.UI.WebControls.TextBox txtAkismetAPIKey;
        protected System.Web.UI.WebControls.CheckBox chkEnableCommentModeration;
        protected Subtext.Web.Controls.HelpToolTip helpCommentModeration;
        protected System.Web.UI.WebControls.CheckBox chkEnableCaptcha;
        protected Subtext.Web.Controls.HelpToolTip helpCaptcha;
        protected System.Web.UI.WebControls.CheckBox chkAllowDuplicates;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip4;
        protected Subtext.Web.Controls.HelpToolTip HelpToolTip2;
        protected System.Web.UI.WebControls.TextBox txtCommentDelayIntervalMinutes;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip3;
        protected System.Web.UI.WebControls.TextBox txtDaysTillCommentsClosed;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip7;
        protected System.Web.UI.WebControls.TextBox txtNumberOfRecentComments;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip8;
        protected System.Web.UI.WebControls.TextBox txtRecentCommentsLength;
        protected System.Web.UI.WebControls.Button lkbPost;
    }
}
