//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class Configure {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Edit;
        protected System.Web.UI.WebControls.TextBox txbTitle;
        protected System.Web.UI.WebControls.TextBox txbSubtitle;
        protected System.Web.UI.WebControls.TextBox txbUser;
        protected System.Web.UI.WebControls.TextBox txbAuthor;
        protected System.Web.UI.WebControls.TextBox txbAuthorEmail;
        protected System.Web.UI.WebControls.DropDownList ddlSkin;
        protected System.Web.UI.WebControls.CheckBox ckbAllowServiceAccess;
        protected MagicAjax.UI.Controls.AjaxPanel ajaxTimezone;
        protected Subtext.Web.Controls.HelpToolTip hlpTimeZone;
        protected System.Web.UI.WebControls.DropDownList ddlTimezone;
        protected System.Web.UI.WebControls.Label lblCurrentTime;
        protected System.Web.UI.WebControls.Label lblServerTime;
        protected System.Web.UI.WebControls.Label lblServerTimeZone;
        protected System.Web.UI.WebControls.DropDownList ddlLangLocale;
        protected System.Web.UI.WebControls.DropDownList ddlItemCount;
        protected System.Web.UI.WebControls.DropDownList ddlCategoryListPostCount;
        protected Subtext.Web.Controls.HelpToolTip HelpToolTip1;
        protected System.Web.UI.WebControls.TextBox txbSecondaryCss;
        protected System.Web.UI.WebControls.TextBox txbNews;
        protected System.Web.UI.WebControls.Button btnPost;
    }
}
