//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class Confirm {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel HeaderSection;
        protected System.Web.UI.WebControls.Label lblOutput;
        protected System.Web.UI.WebControls.Button lkbContinue;
        protected System.Web.UI.WebControls.Button lkbYes;
        protected System.Web.UI.WebControls.Button lkbNo;
    }
}
