//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class EditCategories {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Edit;
        protected System.Web.UI.WebControls.DataGrid dgrItems;
        protected System.Web.UI.WebControls.PlaceHolder Add;
        protected System.Web.UI.WebControls.RequiredFieldValidator valtxbNewTitleRequired;
        protected System.Web.UI.WebControls.TextBox txbNewTitle;
        protected System.Web.UI.WebControls.CheckBox ckbNewIsActive;
        protected System.Web.UI.WebControls.TextBox txbNewDescription;
        protected System.Web.UI.WebControls.Button lkbPost;
    }
}
