//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class EditKeyWords {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected System.Web.UI.WebControls.Repeater rprSelectionList;
        protected Subtext.Web.Controls.PagingControl resultsPager;
        protected System.Web.UI.WebControls.Button btnCreate;
        protected System.Web.UI.WebControls.PlaceHolder Edit;
        protected System.Web.UI.WebControls.TextBox txbWord;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox txbText;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator2;
        protected System.Web.UI.WebControls.TextBox txbUrl;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator3;
        protected System.Web.UI.WebControls.TextBox txbTitle;
        protected System.Web.UI.WebControls.CheckBox chkNewWindow;
        protected System.Web.UI.WebControls.CheckBox chkFirstOnly;
        protected System.Web.UI.WebControls.CheckBox chkCaseSensitive;
        protected System.Web.UI.WebControls.Button lkbPost;
        protected System.Web.UI.WebControls.Button lkbCancel;
    }
}
