//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class Feedback {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected System.Web.UI.WebControls.CheckBox cbShowOnlyComments;
        protected System.Web.UI.WebControls.RadioButtonList rbFeedbackFilter;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Results;
        protected System.Web.UI.WebControls.Repeater rprSelectionList;
        protected Subtext.Web.Controls.PagingControl resultsPager;
        protected System.Web.UI.WebControls.Button btnDelete;
        protected System.Web.UI.WebControls.Button btnDestroy;
        protected System.Web.UI.WebControls.Button btnConfirmSpam;
        protected System.Web.UI.WebControls.Button btnApprove;
        protected System.Web.UI.WebControls.Button btnEmpty;
    }
}
