//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class PluginListPage {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected System.Web.UI.WebControls.Repeater pluginListRpt;
        protected Subtext.Web.Controls.PagingControl resultsPager;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel View;
		protected Subtext.Web.Admin.WebUI.AdvancedPanel Edit;
    }
}
