//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class PluginListPage {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected System.Web.UI.WebControls.Repeater pluginListRpt;
        protected Subtext.Web.Controls.PagingControl resultsPager;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel View;
        protected System.Web.UI.WebControls.Label pluginViewName;
        protected System.Web.UI.WebControls.Label pluginViewGuid;
        protected System.Web.UI.WebControls.Label pluginViewAuthor;
        protected System.Web.UI.WebControls.Label pluginViewCompany;
        protected System.Web.UI.WebControls.Label pluginViewCopyright;
        protected System.Web.UI.WebControls.HyperLink pluginViewHomepage;
        protected System.Web.UI.WebControls.Label pluginViewVersion;
        protected System.Web.UI.WebControls.Label pluginViewDescription;
        protected System.Web.UI.WebControls.Button lkbCancel;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Edit;
        protected System.Web.UI.WebControls.Label pluginEditName;
        protected System.Web.UI.WebControls.PlaceHolder pluginSetting;
        protected System.Web.UI.WebControls.Button lkbPost;
        protected System.Web.UI.WebControls.Button lkbEditCancel;
    }
}
