//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class EditPreferences {
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Edit;
        protected System.Web.UI.WebControls.DropDownList ddlPublished;
        protected System.Web.UI.WebControls.DropDownList ddlExpandAdvanced;
        protected Subtext.Web.Controls.HelpToolTip Helptooltip4;
        protected System.Web.UI.WebControls.CheckBox chkAutoGenerate;
        protected System.Web.UI.WebControls.Button lkbUpdate;
    }
}
