//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Admin.Pages {
    
    public partial class Referrers {
        protected Subtext.Web.Admin.WebUI.MessagePanel Messages;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Results;
        protected System.Web.UI.WebControls.Repeater rprSelectionList;
        protected Subtext.Web.Controls.PagingControl resultsPager;
        protected Subtext.Web.Admin.WebUI.AdvancedPanel Edit;
        protected System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected System.Web.UI.WebControls.TextBox txbTitle;
        protected System.Web.UI.WebControls.RequiredFieldValidator Requiredfieldvalidator3;
        protected System.Web.UI.WebControls.TextBox txbUrl;
        protected System.Web.UI.WebControls.TextBox txbBody;
        protected System.Web.UI.WebControls.Button lkbPost;
        protected System.Web.UI.WebControls.Button lkbCancel;
    }
}
