//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Plugins.Examples.TestPlugin
{
	public partial class settings
	{
		protected System.Web.UI.WebControls.TextBox txbValue1;
		protected System.Web.UI.WebControls.CheckBox chkOption;
		protected System.Web.UI.WebControls.TextBox txbValue2;
	}
}
