//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Web.Controls.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subtext.Web.Controls.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to height must be greater than {0}..
        /// </summary>
        public static string ArgumentOutOfRange_Height {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width must be greater than {0}..
        /// </summary>
        public static string ArgumentOutOfRange_Width {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted encoded text &apos;{0}&apos; was not valid..
        /// </summary>
        public static string CaptchaExpired_EncryptedTextNotValid {
            get {
                return ResourceManager.GetString("CaptchaExpired_EncryptedTextNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha image expired, probably due to recompile making the key out of synch..
        /// </summary>
        public static string CaptchaExpired_KeyOutOfSynch {
            get {
                return ResourceManager.GetString("CaptchaExpired_KeyOutOfSynch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User waited too long to submit captcha.
        /// </summary>
        public static string CaptchaExpired_WaitedTooLong {
            get {
                return ResourceManager.GetString("CaptchaExpired_WaitedTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but this form has expired. Please try again..
        /// </summary>
        public static string Message_FormExpired {
            get {
                return ResourceManager.GetString("Message_FormExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the correct word.
        /// </summary>
        public static string Message_PleaseEnterCorrectWord {
            get {
                return ResourceManager.GetString("Message_PleaseEnterCorrectWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptchaExpired Exception thrown..
        /// </summary>
        public static string Warning_CaptchaExpired {
            get {
                return ResourceManager.GetString("Warning_CaptchaExpired", resourceCulture);
            }
        }
    }
}
