//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.Plugins.Core.CommunityCredits
{
	public partial class settings
	{
		protected System.Web.UI.WebControls.PlaceHolder overridableConfiguration;
		protected System.Web.UI.WebControls.PlaceHolder notOverridableConfiguration;
		protected System.Web.UI.WebControls.TextBox affiliateCode;
		protected System.Web.UI.WebControls.TextBox affiliateKey;
		protected System.Web.UI.WebControls.Literal globalAffiliateCode;
		protected System.Web.UI.WebControls.Literal globalAffiliateKey;
		protected System.Web.UI.WebControls.Literal effectiveAffiliateCode;
		protected System.Web.UI.WebControls.Literal effectiveAffiliateKey;
	}
}
