//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Subtext.BlogML.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Subtext.BlogML.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array cannot be null..
        /// </summary>
        internal static string ArgumentNull_Array {
            get {
                return ResourceManager.GetString("ArgumentNull_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one element in the specified array was null..
        /// </summary>
        internal static string ArgumentNull_ArrayElement {
            get {
                return ResourceManager.GetString("ArgumentNull_ArrayElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a null value within an array..
        /// </summary>
        internal static string ArgumentNull_ArrayValue {
            get {
                return ResourceManager.GetString("ArgumentNull_ArrayValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly cannot be null..
        /// </summary>
        internal static string ArgumentNull_Assembly {
            get {
                return ResourceManager.GetString("ArgumentNull_Assembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyName cannot be null..
        /// </summary>
        internal static string ArgumentNull_AssemblyName {
            get {
                return ResourceManager.GetString("ArgumentNull_AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssemblyName.Name cannot be null or an empty string..
        /// </summary>
        internal static string ArgumentNull_AssemblyNameName {
            get {
                return ResourceManager.GetString("ArgumentNull_AssemblyNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffer cannot be null..
        /// </summary>
        internal static string ArgumentNull_Buffer {
            get {
                return ResourceManager.GetString("ArgumentNull_Buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be null..
        /// </summary>
        internal static string ArgumentNull_Collection {
            get {
                return ResourceManager.GetString("ArgumentNull_Collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary cannot be null..
        /// </summary>
        internal static string ArgumentNull_Dictionary {
            get {
                return ResourceManager.GetString("ArgumentNull_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name cannot be null..
        /// </summary>
        internal static string ArgumentNull_FileName {
            get {
                return ResourceManager.GetString("ArgumentNull_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null..
        /// </summary>
        internal static string ArgumentNull_Generic {
            get {
                return ResourceManager.GetString("ArgumentNull_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Graph cannot be null..
        /// </summary>
        internal static string ArgumentNull_Graph {
            get {
                return ResourceManager.GetString("ArgumentNull_Graph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUID cannot be null..
        /// </summary>
        internal static string ArgumentNull_GUID {
            get {
                return ResourceManager.GetString("ArgumentNull_GUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key cannot be null..
        /// </summary>
        internal static string ArgumentNull_Key {
            get {
                return ResourceManager.GetString("ArgumentNull_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member at position {0} was null..
        /// </summary>
        internal static string ArgumentNull_NullMember {
            get {
                return ResourceManager.GetString("ArgumentNull_NullMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object cannot be null..
        /// </summary>
        internal static string ArgumentNull_Obj {
            get {
                return ResourceManager.GetString("ArgumentNull_Obj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path cannot be null..
        /// </summary>
        internal static string ArgumentNull_Path {
            get {
                return ResourceManager.GetString("ArgumentNull_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider cannot be null.
        /// </summary>
        internal static string ArgumentNull_Provider {
            get {
                return ResourceManager.GetString("ArgumentNull_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream cannot be null..
        /// </summary>
        internal static string ArgumentNull_Stream {
            get {
                return ResourceManager.GetString("ArgumentNull_Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String reference not set to an instance of a String..
        /// </summary>
        internal static string ArgumentNull_String {
            get {
                return ResourceManager.GetString("ArgumentNull_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type cannot be null..
        /// </summary>
        internal static string ArgumentNull_Type {
            get {
                return ResourceManager.GetString("ArgumentNull_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI cannot be null..
        /// </summary>
        internal static string ArgumentNull_Uri {
            get {
                return ResourceManager.GetString("ArgumentNull_Uri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string ArgumentNull_WithParamName {
            get {
                return ResourceManager.GetString("ArgumentNull_WithParamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection string matches the key &apos;{0}&apos;..
        /// </summary>
        internal static string Configuration_KeyNotFound {
            get {
                return ResourceManager.GetString("Configuration_KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BlogMl provider did not set the context..
        /// </summary>
        internal static string InvalidOperation_BlogMLNullContext {
            get {
                return ResourceManager.GetString("InvalidOperation_BlogMLNullContext", resourceCulture);
            }
        }
    }
}
